<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Conference rooms"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="3.257">
  <properties />
            <testcase name="verifyTotalConferenceRooms" time="3.257" classname="org.rm.automation.admin.tests.conferenceRooms.VerifyTotalConferenceRooms">
                <failure type="java.lang.AssertionError"
                  message="expected:&lt;Total Items: 0&gt; but was:&lt;Total Items: 3&gt;"
              >
<![CDATA[java.lang.AssertionError: expected:<Total Items: 0> but was:<Total Items: 3>
  org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
  org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
  org.rm.automation.admin.tests.conferenceRooms.VerifyTotalConferenceRooms.verifyTotalConferenceRooms(VerifyTotalConferenceRooms.java:52)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
  org.testng.TestNG.run(TestNG.java:1032)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
